name = "sentri"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SCAN_HISTORY"
id = "f89dcdf8fc0b41029362a4512f28c3c4"
preview_id = "f89dcdf8fc0b41029362a4512f28c3c4"